//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recepcaoHomolog
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiCy", Namespace="InvoiCy")]
    public partial class InvoiCy : object
    {
        
        private recepcaoHomolog.InvoiCyRecepcaoCabecalho CabecalhoField;
        
        private recepcaoHomolog.InvoiCyRecepcaoInformacoes InformacoesField;
        
        private recepcaoHomolog.InvoiCy.DadosType DadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public recepcaoHomolog.InvoiCyRecepcaoCabecalho Cabecalho
        {
            get
            {
                return this.CabecalhoField;
            }
            set
            {
                this.CabecalhoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public recepcaoHomolog.InvoiCyRecepcaoInformacoes Informacoes
        {
            get
            {
                return this.InformacoesField;
            }
            set
            {
                this.InformacoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public recepcaoHomolog.InvoiCy.DadosType Dados
        {
            get
            {
                return this.DadosField;
            }
            set
            {
                this.DadosField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="InvoiCy.DadosType", Namespace="InvoiCy", ItemName="DadosItem")]
        public class DadosType : System.Collections.Generic.List<recepcaoHomolog.InvoiCyRecepcaoDadosItem>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiCyRecepcao.Cabecalho", Namespace="InvoiCy")]
    public partial class InvoiCyRecepcaoCabecalho : object
    {
        
        private string EmpPKField;
        
        private string EmpCKField;
        
        private string EmpCOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string EmpPK
        {
            get
            {
                return this.EmpPKField;
            }
            set
            {
                this.EmpPKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string EmpCK
        {
            get
            {
                return this.EmpCKField;
            }
            set
            {
                this.EmpCKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string EmpCO
        {
            get
            {
                return this.EmpCOField;
            }
            set
            {
                this.EmpCOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiCyRecepcao.Informacoes", Namespace="InvoiCy")]
    public partial class InvoiCyRecepcaoInformacoes : object
    {
        
        private string TextoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Texto
        {
            get
            {
                return this.TextoField;
            }
            set
            {
                this.TextoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiCyRecepcao.DadosItem", Namespace="InvoiCy")]
    public partial class InvoiCyRecepcaoDadosItem : object
    {
        
        private string DocumentoField;
        
        private string ParametrosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Documento
        {
            get
            {
                return this.DocumentoField;
            }
            set
            {
                this.DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Parametros
        {
            get
            {
                return this.ParametrosField;
            }
            set
            {
                this.ParametrosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoicyretorno", Namespace="InvoiCy")]
    public partial class Invoicyretorno : object
    {
        
        private recepcaoHomolog.Invoicyretorno.MensagemType MensagemField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public recepcaoHomolog.Invoicyretorno.MensagemType Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Invoicyretorno.MensagemType", Namespace="InvoiCy", ItemName="MensagemItem")]
        public class MensagemType : System.Collections.Generic.List<recepcaoHomolog.InvoiCyRetornoMensagemItem>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiCyRetorno.MensagemItem", Namespace="InvoiCy")]
    public partial class InvoiCyRetornoMensagemItem : object
    {
        
        private int CodigoField;
        
        private string DescricaoField;
        
        private recepcaoHomolog.InvoiCyRetornoMensagemItem.DocumentosType DocumentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public recepcaoHomolog.InvoiCyRetornoMensagemItem.DocumentosType Documentos
        {
            get
            {
                return this.DocumentosField;
            }
            set
            {
                this.DocumentosField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="InvoiCyRetorno.MensagemItem.DocumentosType", Namespace="InvoiCy", ItemName="DocumentosItem")]
        public class DocumentosType : System.Collections.Generic.List<recepcaoHomolog.InvoiCyRetornoMensagemItem.DocumentosItem>
        {
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="InvoiCyRetorno.MensagemItem.DocumentosItem", Namespace="InvoiCy")]
        public partial class DocumentosItem : object
        {
            
            private string DocumentoField;
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Documento
            {
                get
                {
                    return this.DocumentoField;
                }
                set
                {
                    this.DocumentoField = value;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="InvoiCy", ConfigurationName="recepcaoHomolog.recepcaoSoapPort")]
    public interface recepcaoSoapPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="InvoiCyaction/ARECEPCAO.Execute", ReplyAction="*")]
        recepcaoHomolog.ExecuteResponse Execute(recepcaoHomolog.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="InvoiCyaction/ARECEPCAO.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<recepcaoHomolog.ExecuteResponse> ExecuteAsync(recepcaoHomolog.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recepcao.Execute", Namespace="InvoiCy", Order=0)]
        public recepcaoHomolog.ExecuteRequestBody Body;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(recepcaoHomolog.ExecuteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="InvoiCy")]
    public partial class ExecuteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public recepcaoHomolog.InvoiCy Invoicyrecepcao;
        
        public ExecuteRequestBody()
        {
        }
        
        public ExecuteRequestBody(recepcaoHomolog.InvoiCy Invoicyrecepcao)
        {
            this.Invoicyrecepcao = Invoicyrecepcao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recepcao.ExecuteResponse", Namespace="InvoiCy", Order=0)]
        public recepcaoHomolog.ExecuteResponseBody Body;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(recepcaoHomolog.ExecuteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="InvoiCy")]
    public partial class ExecuteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public recepcaoHomolog.Invoicyretorno Invoicyretorno;
        
        public ExecuteResponseBody()
        {
        }
        
        public ExecuteResponseBody(recepcaoHomolog.Invoicyretorno Invoicyretorno)
        {
            this.Invoicyretorno = Invoicyretorno;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface recepcaoSoapPortChannel : recepcaoHomolog.recepcaoSoapPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class recepcaoSoapPortClient : System.ServiceModel.ClientBase<recepcaoHomolog.recepcaoSoapPort>, recepcaoHomolog.recepcaoSoapPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public recepcaoSoapPortClient() : 
                base(recepcaoSoapPortClient.GetDefaultBinding(), recepcaoSoapPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.recepcaoSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recepcaoSoapPortClient(EndpointConfiguration endpointConfiguration) : 
                base(recepcaoSoapPortClient.GetBindingForEndpoint(endpointConfiguration), recepcaoSoapPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recepcaoSoapPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(recepcaoSoapPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recepcaoSoapPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(recepcaoSoapPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recepcaoSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public recepcaoHomolog.ExecuteResponse Execute(recepcaoHomolog.ExecuteRequest request)
        {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<recepcaoHomolog.ExecuteResponse> ExecuteAsync(recepcaoHomolog.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.recepcaoSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.recepcaoSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("https://homolog.invoicy.com.br/arecepcao.aspx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return recepcaoSoapPortClient.GetBindingForEndpoint(EndpointConfiguration.recepcaoSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return recepcaoSoapPortClient.GetEndpointAddress(EndpointConfiguration.recepcaoSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            recepcaoSoapPort,
        }
    }
}
